apiVersion: apps/v1
kind: Deployment
metadata:
    name: node-devcanilnew
spec:
    selector:
        matchLabels:
            app: node-devcanilnew
    template:
        metadata:
            labels:
                app: node-devcanilnew
        spec:
            containers:
                - name: node-devcanilnew
                  image: node-devcanilnew
                  imagePullPolicy: IfNotPresent
                  env:
                    - name: PORT
                      value: "4000"
                  resources:
                    limits:
                        cpu: 128m
                        memory: 64Mi
                  ports:
                    - containerPort: 4000
                      protocol: TCP
                      name: http
---
apiVersion: v1
kind: Service
metadata:
    name: node-devcanilnew
spec:
    selector:
        app: node-devcanilnew
    ports:
        - port: 4000
          targetPort: http
